# Generated by Django 5.0.4 on 2024-04-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='language_logos/')),
                ('detailed_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PythonFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='framework_logos/')),
                ('detailed_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PythonLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='library_logos/')),
                ('detailed_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PythonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
