# Generated by Django 5.0.4 on 2024-04-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonlibrary',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pythonlibrary',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='pythonlibrary',
            name='logo',
        ),
    ]
